/** @format */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const CabinetGrotesk = localFont({
  src: "/fonts/CabinetGrotesk/CabinetGrotesk-Regular.otf",
  variable: "--font-Cabinet-Grotesk",
  weight: "400",
});
const AeonikRegular = localFont({
  src: "/fonts/aeonik/Aeonik-Regular.otf ",
  variable: "--font-Aeonik-Regular",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Adora",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CabinetGrotesk} ${AeonikRegular} antialiased`}>{children}</body>
    </html>
  );
}
