/** @format */

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const CabinetGrotesk = localFont({
  src: "/public/fonts/CabinetGrotesk/",
  variable: "--font-Cabinet-Grotesk",
  weight: "400",
});
const AeonikRegular = localFont({
  src: "/public/fonts/aeonik/",
  variable: "--font-Aeonik-Regular/",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${CabinetGrotesk.variable} ${AeonikRegular.variable} antialiased`}>{children}</body>
    </html>
  );
}
